language: node_js

jobs:
  include:
  - services: mongodb
    before_script:
      - sleep 15
      - mongo mongo_test_db --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
    node_js: 12
    env:
      - database_host: mongodb://127.0.0.1:27017
        database_name: mongo_test_db
        database_username: travis
        database_password: test

  - services: mongodb
    before_script:
      - sleep 15
      - mongo mongo_test_db --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
    node_js: 14
    env:
      - database_host: mongodb://127.0.0.1:27017
        database_name: mongo_test_db
        database_username: travis
        database_password: test

  - services: mysql
    node_js: 12
    before_script:
      - sleep 15
      - mysql -e 'CREATE DATABASE myapp_test;'
    env:
      - database_host: mysql://root@127.0.0.1/myapp_test

  - services: mysql
    node_js: 14
    before_script:
      - sleep 15
      - mysql -e 'CREATE DATABASE myapp_test;'
    env:
      - database_host: mysql://root@127.0.0.1/myapp_test

script:
  - npm test
