name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        mongodb-version: [6.0.3, 5.0.14]

    services:
      mongodb:
        image: mongo:${{ matrix.mongodb-version }}
        environment:
          MONGO_INITDB_ROOT_USERNAME: test_user
          MONGO_INITDB_ROOT_PASSWORD: test_user
        ports:
          - 27017:27017

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # - name: Add database user
      #   run: docker exec -it mongodb mongosh dynamic_record --eval 'db.createUser({user:"test_user",pwd:"test_user",roles:["readWrite"]});'

      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npm test
        env: 
          database_host: "mongodb://test_user:test_user@localhost:27017/dynamic_record"
